if(NOT DEFINED BENCHMARK OR NOT DEFINED GENERATOR OR NOT DEFINED ALLOCATION OR NOT DEFINED OUTPUT_DIR)
  message(FATAL_ERROR "Evidence executable paths and OUTPUT_DIR required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(tool IN ITEMS BENCHMARK GENERATOR ALLOCATION)
  execute_process(COMMAND "${${tool}}" --help RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${tool} help failed: ${result}")
  endif()
  execute_process(COMMAND "${${tool}}" --output x --smoke --smoke RESULT_VARIABLE result)
  if(NOT result EQUAL 2)
    message(FATAL_ERROR "${tool} duplicate option not rejected: ${result}")
  endif()
endforeach()
execute_process(COMMAND "${BENCHMARK}" --output "${OUTPUT_DIR}/benchmark.json" --smoke RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Benchmark smoke failed: ${result}")
endif()
execute_process(COMMAND "${ALLOCATION}" --output "${OUTPUT_DIR}/allocation.json" --smoke RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Allocation smoke failed: ${result}")
endif()
execute_process(COMMAND "${BENCHMARK}" --output "${OUTPUT_DIR}/benchmark-mono12.json" --source-format mono12 --smoke RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Mono12 benchmark smoke failed: ${result}")
endif()
execute_process(COMMAND "${ALLOCATION}" --output "${OUTPUT_DIR}/allocation-mono12.json" --source-format mono12 --smoke RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Mono12 allocation smoke failed: ${result}")
endif()
# Each test run owns a fresh candidate path and never rewrites an old manifest.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef token)
execute_process(COMMAND "${GENERATOR}" --output "${OUTPUT_DIR}/candidate-${token}" --smoke RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Generator smoke failed: ${result}")
endif()
execute_process(COMMAND "${GENERATOR}" --output "${OUTPUT_DIR}/candidate-${token}" --smoke RESULT_VARIABLE result)
if(NOT result EQUAL 2)
  message(FATAL_ERROR "Generator overwrote a nonempty directory")
endif()

if(DEFINED VALIDATOR)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env "LUMORA_EVIDENCE_DIRECTORY=${OUTPUT_DIR}"
    "${VALIDATOR}" --gtest_filter=EvidenceArtifactFiles.* RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Generated artifact validation/mutations failed: ${result}")
  endif()
endif()
