# Exercise the production provenance setup in a tiny C/C++ project. No Qt,
# Processing math, or benchmark workload is needed to reproduce these defects.
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT_DIR OR NOT DEFINED TEST_CASE)
  message(FATAL_ERROR "SOURCE_DIR, OUTPUT_DIR and TEST_CASE are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}/source")
set(test_source "${OUTPUT_DIR}/source")
set(test_binary "${OUTPUT_DIR}/build")
file(WRITE "${test_source}/main.cpp" "int main() { return 0; }\n")
file(WRITE "${test_source}/empty.c" "int unused_c_function(void) { return 0; }\n")
set(project [=[
cmake_minimum_required(VERSION 3.28)
project(EvidenceProvenanceRegression LANGUAGES C CXX)
set(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo;MinSizeRel" CACHE STRING "" FORCE)
add_library(lumora_processing STATIC main.cpp)
add_library(lumora_processing_evidence_support STATIC main.cpp)
add_library(c_context STATIC empty.c)
if(TEST_CASE STREQUAL "language")
  target_compile_options(lumora_processing PRIVATE "$<$<COMPILE_LANGUAGE:CXX>:-DCXX_PROCESSING_ONLY>")
  target_compile_options(lumora_processing_evidence_support PRIVATE "$<$<COMPILE_LANGUAGE:CXX>:-DCXX_EVIDENCE_ONLY>")
else()
  # Literal legal flags with quotes and backslashes. They need JSON escaping
  # after CMake evaluates expressions, independently of shell/compiler quoting.
  set(CMAKE_CXX_FLAGS [==[-DREVIEW_LABEL="review" -DREVIEW_PATH="C:\\review"]==])
endif()
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DREVIEW_DEBUG")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DREVIEW_RELEASE")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} -DREVIEW_RELWITHDEBINFO")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} -DREVIEW_MINSIZEREL")
include("@SOURCE_DIR@/benchmarks/processing/EvidenceProvenance.cmake")
lumora_configure_evidence_provenance("@SOURCE_DIR@")
foreach(config IN ITEMS Debug Release RelWithDebInfo MinSizeRel)
  string(TOUPPER "${config}" config_upper)
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${config}/expected-global.txt" "${CMAKE_CXX_FLAGS}")
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${config}/expected-configuration.txt" "${CMAKE_CXX_FLAGS_${config_upper}}")
endforeach()
]=])
string(CONFIGURE "${project}" project @ONLY)
file(WRITE "${test_source}/CMakeLists.txt" "${project}")
set(configure_arguments -S "${test_source}" -B "${test_binary}" -G "${TEST_GENERATOR}" "-DTEST_CASE=${TEST_CASE}")
if(DEFINED TEST_PLATFORM AND NOT TEST_PLATFORM STREQUAL "")
  list(APPEND configure_arguments -A "${TEST_PLATFORM}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" ${configure_arguments} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
file(WRITE "${OUTPUT_DIR}/configure.log" "${output}${error}")
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Provenance configure/generate failed: ${error}")
endif()
foreach(config IN ITEMS Debug Release RelWithDebInfo MinSizeRel)
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${test_binary}" --config "${config}"
    --target lumora_evidence_provenance --parallel 3 RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(WRITE "${OUTPUT_DIR}/build-${config}.log" "${output}${error}")
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Provenance capture failed for ${config}: ${error}")
  endif()
endforeach()
if(TEST_CASE STREQUAL "language")
  foreach(config IN ITEMS Debug Release RelWithDebInfo MinSizeRel)
    file(READ "${test_binary}/${config}/evidence-config.json" document)
    string(JSON options ERROR_VARIABLE parse_error GET "${document}" compileOptions processing)
    if(NOT parse_error STREQUAL "NOTFOUND" OR NOT options MATCHES "CXX_PROCESSING_ONLY")
      message(FATAL_ERROR "Expected only intended C++ processing options: ${parse_error}; ${options}")
    endif()
    string(JSON options GET "${document}" compileOptions evidence)
    if(NOT options MATCHES "CXX_EVIDENCE_ONLY")
      message(FATAL_ERROR "Expected intended C++ evidence options: ${options}")
    endif()
  endforeach()
else()
  foreach(config IN ITEMS Debug Release RelWithDebInfo MinSizeRel)
    file(READ "${test_binary}/${config}/evidence-config.json" document)
    string(JSON global ERROR_VARIABLE parse_error GET "${document}" compileOptions global)
    if(NOT parse_error STREQUAL "NOTFOUND")
      message(FATAL_ERROR "Compiler flags must produce valid JSON: ${parse_error}")
    endif()
    string(JSON configuration GET "${document}" compileOptions configuration)
    file(READ "${test_binary}/${config}/expected-global.txt" expected_global)
    file(READ "${test_binary}/${config}/expected-configuration.txt" expected_configuration)
    if(NOT global STREQUAL expected_global OR NOT configuration STREQUAL expected_configuration)
      message(FATAL_ERROR "Flags must round-trip exactly for ${config}: ${global}; ${configuration}")
    endif()
  endforeach()
endif()
message(STATUS "Provenance ${TEST_CASE} regression passed")
