function(require_target name)
  if(NOT TARGET ${name})
    message(FATAL_ERROR "Required target missing: ${name}")
  endif()
endfunction()

function(lumora_verify_milestone_one_targets)
  require_target(lumora_core)
  require_target(lumora_configuration)
  require_target(lumora_diagnostics)
  require_target(lumora_qml_ui)
  require_target(lumora_quick_renderer)
  if(LUMORA_BUILD_LEGACY_WIDGETS_TESTS)
    require_target(lumora_ui)
  elseif(TARGET lumora_ui OR TARGET lumora_ui_tests OR TARGET lumora_integration_tests)
    message(FATAL_ERROR "Widgets targets require LUMORA_BUILD_LEGACY_WIDGETS_TESTS=ON")
  endif()
  require_target(lumora_app)

  if(TARGET lumora_camera_basler AND NOT LUMORA_ENABLE_BASLER)
    message(FATAL_ERROR
      "lumora_camera_basler must not exist when LUMORA_ENABLE_BASLER is OFF")
  endif()
endfunction()
